Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 63
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 23
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 23
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 36
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 43
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&finish_lat=34.0522&finish_lng=-118.2437 HTTP/1.1" 500 70
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=34.0522&end_lng=-118.2437 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=37.7749&end_lng=-122.4194 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=8.9824&end_lng=-79.5199 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=8.9824&end_lng=-79.5199 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=8.9824&end_lng=-79.5199 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=8.9824&end_lng=-79.5199 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 65, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 119, in _calculate_fuel_stops
    route_point = route_points[idx]
TypeError: only integer scalar arrays can be converted to a scalar index
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 94981
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 63, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 117, in _calculate_fuel_stops
    route_point = route_points[idx]
TypeError: only integer scalar arrays can be converted to a scalar index
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 94981
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 63, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 117, in _calculate_fuel_stops
    route_point = route_points[idx]
TypeError: only integer scalar arrays can be converted to a scalar index
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 94981
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 37
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
"GET /route/?start_lat=40.7128&start_lng=-74.0060&end_lat=38.9072&end_lng=-77.0369 HTTP/1.1" 500 47
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 64, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 136, in _calculate_fuel_stops
    distance_from_route = great_circle(
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 276, in __init__
    kilometers += self.measure(a, b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 464, in measure
    a, b = Point(a), Point(b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 175, in __new__
    return cls.from_sequence(seq)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 472, in from_sequence
    return cls(*args)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 188, in __new__
    _normalize_coordinates(latitude, longitude, altitude)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 74, in _normalize_coordinates
    raise ValueError('Latitude must be in the [-90; 90] range.')
ValueError: Latitude must be in the [-90; 90] range.
"GET /route/?start_lat=34.0522&start_lng=-118.2437&end_lat=36.1699&end_lng=-115.1398 HTTP/1.1" 500 126645
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 64, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 136, in _calculate_fuel_stops
    distance_from_route = great_circle(
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 276, in __init__
    kilometers += self.measure(a, b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 464, in measure
    a, b = Point(a), Point(b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 175, in __new__
    return cls.from_sequence(seq)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 472, in from_sequence
    return cls(*args)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 188, in __new__
    _normalize_coordinates(latitude, longitude, altitude)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 74, in _normalize_coordinates
    raise ValueError('Latitude must be in the [-90; 90] range.')
ValueError: Latitude must be in the [-90; 90] range.
"GET /route/?start_lat=34.0522&start_lng=-118.2437&end_lat=36.1699&end_lng=-115.1398 HTTP/1.1" 500 126645
Internal Server Error: /route/
Traceback (most recent call last):
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 64, in get
    fuel_stops, total_cost = self._calculate_fuel_stops(route_data['coordinates'],
  File "C:\Users\zagor\Documents\django-api\api\views.py", line 136, in _calculate_fuel_stops
    distance_from_route = great_circle(
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 276, in __init__
    kilometers += self.measure(a, b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\distance.py", line 464, in measure
    a, b = Point(a), Point(b)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 175, in __new__
    return cls.from_sequence(seq)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 472, in from_sequence
    return cls(*args)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 188, in __new__
    _normalize_coordinates(latitude, longitude, altitude)
  File "C:\Users\zagor\AppData\Local\Programs\Python\Python39\lib\site-packages\geopy\point.py", line 74, in _normalize_coordinates
    raise ValueError('Latitude must be in the [-90; 90] range.')
ValueError: Latitude must be in the [-90; 90] range.
"GET /route/?start_lat=34.0522&start_lng=-118.2437&end_lat=36.1699&end_lng=-115.1398 HTTP/1.1" 500 126645
